//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhChon
    {
        public int MaSo { get; set; }
        public string MS_ThanhVien { get; set; }
        public int MS_BaiNhanXet { get; set; }
        public bool TinhTrang { get; set; }
        public System.DateTime ThoiGian { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual BaiNhanXet BaiNhanXet { get; set; }
    }
}
