//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phim
    {
        public Phim()
        {
            this.BaiNhanXet = new HashSet<BaiNhanXet>();
            this.DanhGia = new HashSet<DanhGia>();
            this.DanhSachPhimYeuThich = new HashSet<DanhSachPhimYeuThich>();
        }
    
        public int MaSo { get; set; }
        public string TenPhim { get; set; }
        public string NoiDung { get; set; }
        public string URL_Trailer { get; set; }
        public Nullable<double> DiemDanhGia { get; set; }
        public Nullable<int> MS_TheLoai { get; set; }
        public Nullable<double> ThoiLuong { get; set; }
        public string DienVien { get; set; }
        public string DaoDien { get; set; }
        public Nullable<int> MS_NuocSX { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<System.DateTime> NgayPhatHanh { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public string AnhBanner { get; set; }
    
        public virtual ICollection<BaiNhanXet> BaiNhanXet { get; set; }
        public virtual ICollection<DanhGia> DanhGia { get; set; }
        public virtual DanhMucNuocSanXuat DanhMucNuocSanXuat { get; set; }
        public virtual DanhMucTheLoai DanhMucTheLoai { get; set; }
        public virtual ICollection<DanhSachPhimYeuThich> DanhSachPhimYeuThich { get; set; }
    }
}
