//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThanhVien
    {
        public string HoTen { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public string Avatar { get; set; }
        public string MS_TaiKhoan { get; set; }
        public int MaSo { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
