//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TURBO_PHIMEntities : DbContext
    {
        public TURBO_PHIMEntities()
            : base("name=TURBO_PHIMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<AspNetRoles> AspNetRoles { get; set; }
        public DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public DbSet<AspNetUsers> AspNetUsers { get; set; }
        public DbSet<BaiNhanXet> BaiNhanXet { get; set; }
        public DbSet<BangThamSo> BangThamSo { get; set; }
        public DbSet<BinhChon> BinhChon { get; set; }
        public DbSet<BinhLuan> BinhLuan { get; set; }
        public DbSet<DanhGia> DanhGia { get; set; }
        public DbSet<DanhMucNuocSanXuat> DanhMucNuocSanXuat { get; set; }
        public DbSet<DanhMucTheLoai> DanhMucTheLoai { get; set; }
        public DbSet<DanhSachPhimYeuThich> DanhSachPhimYeuThich { get; set; }
        public DbSet<Phim> Phim { get; set; }
        public DbSet<ThanhVien> ThanhVien { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
