// <auto-generated />
namespace Turbo_Phim.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class DayRegister : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DayRegister));
        
        string IMigrationMetadata.Id
        {
            get { return "201505291914052_DayRegister"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
